name: "Báo Cáo Bất Thường [Anomaly Report]"
description: Phát hiện một trục trặc, G.L.I.T.C.H, hoặc hành vi không mong muốn của [L.P.A].
title: "[Anomaly] "
labels: ["bug", "anomaly", "cần-kiểm-tra"]
body:
  - type: markdown
    attributes:
      value: |
        **PHÁT HIỆN TÍN HIỆU BẤT THƯỜNG?**
        Cảm ơn bạn đã dành thời gian báo cáo. Cung cấp càng nhiều chi tiết càng tốt sẽ giúp chúng tôi định vị và vá lỗi nhanh hơn.

  - type: textarea
    id: anomaly-description
    attributes:
      label: Mô Tả Lỗi Bất Thường
      description: Một mô tả rõ ràng, súc tích về G.L.I.T.C.H bạn đã phát hiện.
      placeholder: "Khi tôi nhấn nút 'Bắt đầu Auto Celeb', hệ thống bị treo ở..."
    validations:
      required: true

  - type: textarea
    id: replication-steps
    attributes:
      label: Các Bước Tái Hiện Lỗi
      description: Giao thức chính xác để chúng tôi có thể tái lập trình lỗi này.
      placeholder: |
        1. Truy cập vào [URL]...
        2. Nhấn vào [Nút Nào]...
        3. Cuộn xuống [Phần Nào]...
        4. Quan sát [Lỗi Xảy Ra]...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Hành Vi Mong Đợi
      description: Mô tả kết quả mà hệ thống lẽ ra phải thực hiện.
      placeholder: "Lẽ ra hệ thống phải tự động..."
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Bằng Chứng (Ảnh / Video / Logs)
      description: "Dán ảnh chụp màn hình, video, hoặc dữ liệu logs từ Bảng Điều Khiển (Nhấn F12 -> Console) vào đây."
      placeholder: "[Kéo và thả hình ảnh hoặc dán logs lỗi tại đây]"

  - type: dropdown
    id: browser
    attributes:
      label: Trình Duyệt
      description: Bạn đang vận hành Lõi [L.P.A] trên trình duyệt nào?
      options:
        - Chrome (PC)
        - Edge (PC)
        - Firefox (PC)
        - Kiwi Browser (Mobile)
        - Khác (Ghi rõ ở dưới)
    validations:
      required: true

  - type: input
    id: lpa-version
    attributes:
      label: Phiên Bản Lõi [L.P.A]
      description: Bạn có thể tìm thấy trong phần đầu của code script.
      placeholder: "v13.0"
