name: "Yêu Cầu Hỗ Trợ Kỹ Thuật [Support Protocol]"
description: Đặt câu hỏi hoặc yêu cầu trợ giúp khi gặp sự cố cài đặt/sử dụng (Không phải lỗi).
title: "[Support] "
labels: ["support", "question", "hỗ-trợ"]
body:
  - type: markdown
    attributes:
      value: |
        **CẦN HỖ TRỢ KẾT NỐI?**
        Nếu bạn gặp sự cố khi cài đặt hoặc sử dụng (và nó không phải là một lỗi), hãy mô tả chi tiết tại đây.
        **Lưu ý:** Vui lòng kiểm tra mục [Giải Đáp Thắc Mắc (FAQ)](https://github.com/Pinnnndz/locket-autocelebrity-v4#gi%E1%BA%A3i-%C4%91%C3%A1p-th%E1%BA%AFc-m%E1%BAAFc-faq) trong README trước khi gửi.

  - type: textarea
    id: support-question
    attributes:
      label: Mô Tả Vấn Đề
      description: "Bạn cần hỗ trợ về vấn đề gì? Mô tả chi tiết các bước bạn đã thực hiện và bạn bị kẹt ở đâu."
      placeholder: "Tôi đã cài đặt Tampermonkey và Script, nhưng khi vào trang Locketbinhake thì không thấy Bảng Điều Khiển..."
    validations:
      required: true

  - type: textarea
    id: what-you-tried
    attributes:
      label: Những Gì Bạn Đã Thử
      description: "Liệt kê các bước bạn đã thử để tự giải quyết (VD: Đọc FAQ, cài lại script, F5, dùng VPN...)."
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Trình Duyệt
      description: Bạn đang sử dụng trình duyệt nào?
      options:
        - Chrome (PC)
        - Edge (PC)
        - Firefox (PC)
        - Kiwi Browser (Mobile)
        - Khác
    validations:
      required: true
