name: "Đề Xuất Nâng Cấp [Upgrade Proposal]"
description: Đề xuất một tính năng, một kiến trúc mới, hoặc một ý tưởng tiến hóa cho [L.P.A].
title: "[Upgrade] "
labels: ["enhancement", "upgrade", "ý-tưởng"]
body:
  - type: markdown
    attributes:
      value: |
        **BẠN CÓ MỘT BẢN THIẾT KẾ NÂNG CẤP?**
        Chúng tôi rất sẵn lòng nghe ý tưởng của bạn để giúp [L.P.A] tiến hóa.

  - type: textarea
    id: problem-statement
    attributes:
      label: Vấn Đề Cần Giải Quyết
      description: Đề xuất này có liên quan đến một vấn đề hiện tại không?
      placeholder: "Hiện tại, tôi phải tốn thời gian làm [Thao Tác Thủ Công]... Tôi tin rằng [L.P.A] có thể tự động hóa việc này."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Giải Pháp/Bản Nâng Cấp Đề Xuất
      description: Mô tả chi tiết về bản nâng cấp bạn muốn thấy. Nó nên hoạt động như thế nào?
      placeholder: "Tôi đề xuất thêm một nút mới trong Bảng Điều Khiển tên là [...], khi nhấn vào, nó sẽ tự động [...]."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Các Giải Pháp Thay Thế (Nếu có)
      description: Bạn có nghĩ đến bất kỳ giải pháp hoặc kiến trúc nào khác không?

  - type: textarea
    id: additional-context
    attributes:
      label: Bối Cảnh Bổ Sung
      description: "Thêm bất kỳ thông tin, hình ảnh mô phỏng (mock-up), hoặc liên kết tham khảo nào tại đây."
